version: '3.8'

services:
  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    ports:
      - "8001:8000"

  payment-service:
    build: ./payment-service
    env_file:
      - ./payment-service/.env
    ports:
      - "8002:8000"

  delivery-service:
    build: ./delivery-service
    env_file:
      - ./delivery-service/.env
    ports:
      - "8003:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: orders,payments,delivery
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh