version: '3.8'

services:
  order-service:
    build: ./order
    env_file:
      - ./order/.env
    ports:
      - "8001:8000"
    volumes:
      - ./order:/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  order-worker:
    build: ./order
    command: celery -A src.tasks.celery_app worker --loglevel=info -Q order_queue
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  payment-service:
    build: ./payment
    env_file:
      - ./payment/.env
    ports:
      - "8002:8000"
    volumes:
      - ./payment:/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  payment-worker:
    build: ./payment
    command: celery -A src.tasks.celery_app worker --loglevel=info -Q payment_queue
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  delivery-service:
    build: ./delivery
    env_file:
      - ./delivery/.env
    ports:
      - "8003:8000"
    volumes:
      - ./delivery:/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  delivery-worker:
    build: ./delivery
    command: celery -A src.tasks.celery_app worker --loglevel=info -Q delivery_queue
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: orders,payments,delivery
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  flower:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_healthy