version: '3.8'

services:
  order-service:
    build: ./order
    env_file:
      - ./order/.env
    ports:
      - "8001:8000"
    volumes:
      - ./order:/app
  
  order-worker:
    build: ./order
    command: celery -A src.tasks.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - db

  payment-service:
    build: ./payment
    env_file:
      - ./payment/.env
    ports:
      - "8002:8000"
    volumes:
      - ./payment:/app

  payment-worker:
    build: ./payment
    command: celery -A src.tasks.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - db

  delivery-service:
    build: ./delivery
    env_file:
      - ./delivery/.env
    ports:
      - "8003:8000"
    volumes:
      - ./delivery:/app

  delivery-worker:
    build: ./delivery
    command: celery -A src.tasks.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: orders,payments,delivery
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh